---
swagger: "2.0"
info:
  description: "Floyd API"
  version: "1.0.0"
  title: "Floyd API"
host: "localhost:3000"
basePath: "/v1"
schemes:
- "http"
produces:
- "application/json"
paths:
  /addPhotoToAlbum:
    get:
      tags:
      - "IAlbum"
      summary: "add photo to album"
      description: "add photo to album."
      operationId: "addPhotoToAlbumGet"
      parameters:
      - name: "albumId"
        in: "query"
        required: true
        type: "string"
      - name: "photoName"
        in: "query"
        required: true
        type: "string"
      - name: "photoUrl"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "Profile information for a user"
          schema:
            $ref: "#/definitions/PhotoInfo"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "IAlbum"
  /albumById:
    get:
      tags:
      - "IAlbum"
      summary: "get album info by id"
      description: "album information."
      operationId: "albumByIdGet"
      parameters:
      - name: "albumId"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "Profile information for a user"
          schema:
            $ref: "#/definitions/AlbumInfo"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "IAlbum"
  /allAlbums:
    get:
      tags:
      - "IAlbum"
      summary: "get all user albums"
      description: "album information."
      operationId: "allAlbumsGet"
      parameters:
      - name: "userId"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "Profile information for a user"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/AlbumInfo"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "IAlbum"
  /associateUserWithWeiboId:
    get:
      tags:
      - "ICustomer"
      summary: "associate user information"
      description: "associate information."
      operationId: "associateUserWithWeiboIdGet"
      parameters:
      - name: "wbUserId"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "Profile information for a user"
          schema:
            $ref: "#/definitions/UserInfo"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "ICustomer"
  /createAlbum:
    get:
      tags:
      - "IAlbum"
      summary: "create a new album"
      description: "create album."
      operationId: "createAlbumGet"
      parameters:
      - name: "userId"
        in: "query"
        required: true
        type: "string"
      - name: "albumName"
        in: "query"
        required: true
        type: "string"
      - name: "albumDesc"
        in: "query"
        required: true
        type: "string"
      - name: "cover"
        in: "query"
        required: false
        type: "string"
      responses:
        200:
          description: "Profile information for a user"
          schema:
            $ref: "#/definitions/AlbumInfo"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "IAlbum"
  /photosInAlbum:
    get:
      tags:
      - "IAlbum"
      summary: "get all photos in album"
      description: "all photos in album."
      operationId: "photosInAlbumGet"
      parameters:
      - name: "albumId"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "Profile information for a user"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/PhotoInfo"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "IAlbum"
  /updateUserAvatar:
    get:
      tags:
      - "ICustomer"
      summary: "update user avatar"
      description: "user information."
      operationId: "updateUserAvatarGet"
      parameters:
      - name: "userId"
        in: "query"
        required: true
        type: "string"
      - name: "avatarKey"
        in: "query"
        required: true
        type: "string"
      - name: "avatarHash"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "Profile information for a user"
          schema:
            $ref: "#/definitions/UserInfo"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "ICustomer"
  /updateUserBirthday:
    get:
      tags:
      - "ICustomer"
      summary: "update user birthday"
      description: "user information."
      operationId: "updateUserBirthdayGet"
      parameters:
      - name: "userId"
        in: "query"
        required: true
        type: "string"
      - name: "userBirthday"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "Profile information for a user"
          schema:
            $ref: "#/definitions/UserInfo"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "ICustomer"
  /updateUserName:
    get:
      tags:
      - "ICustomer"
      summary: "update user name"
      description: "user information."
      operationId: "updateUserNameGet"
      parameters:
      - name: "userId"
        in: "query"
        required: true
        type: "string"
      - name: "userName"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "Profile information for a user"
          schema:
            $ref: "#/definitions/UserInfo"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "ICustomer"
  /uploadToken:
    get:
      tags:
      - "IFile"
      summary: "qiniu uoload token"
      description: "get qiniu upload token."
      operationId: "uploadTokenGet"
      parameters: []
      responses:
        200:
          description: "Profile information for a user"
          schema:
            $ref: "#/definitions/TokenInfo"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "IFile"
  /userById:
    get:
      tags:
      - "ICustomer"
      summary: "get user information"
      description: "user information."
      operationId: "userByIdGet"
      parameters:
      - name: "userId"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "Profile information for a user"
          schema:
            $ref: "#/definitions/UserInfo"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "ICustomer"
  /userByWeiboId:
    get:
      tags:
      - "ICustomer"
      summary: "get user information"
      description: "user information."
      operationId: "userByWeiboIdGet"
      parameters:
      - name: "wbUserId"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "Profile information for a user"
          schema:
            $ref: "#/definitions/UserInfo"
        default:
          description: "Unexpected error"
          schema:
            $ref: "#/definitions/Error"
      x-swagger-router-controller: "ICustomer"
definitions:
  TokenInfo:
    type: "object"
    properties:
      token:
        type: "string"
  UserInfo:
    type: "object"
    properties:
      _id:
        type: "string"
      birthday:
        type: "string"
      name:
        type: "string"
      weiboId:
        type: "string"
      weiboToken:
        type: "string"
      avatarKey:
        type: "string"
      avatarHash:
        type: "string"
      created:
        type: "string"
        format: "date-time"
      modified:
        type: "string"
        format: "date-time"
  AlbumInfo:
    type: "object"
    properties:
      _id:
        type: "string"
      name:
        type: "string"
      desc:
        type: "string"
      cover:
        type: "string"
      created:
        type: "string"
        format: "date-time"
      modified:
        type: "string"
        format: "date-time"
  PhotoInfo:
    type: "object"
    properties:
      _id:
        type: "string"
      name:
        type: "string"
      desc:
        type: "string"
      url:
        type: "string"
      created:
        type: "string"
        format: "date-time"
      modified:
        type: "string"
        format: "date-time"
  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      message:
        type: "string"
      fields:
        type: "string"
